DROP TABLE `#__litdb_ArticleType`,
	`#__litdb_Audience`,
	`#__litdb_BookType`,
	`#__litdb_Contributor`,
	`#__litdb_ContributorType`,
	`#__litdb_Format`,
	`#__litdb_Journal`,
	`#__litdb_Literature`,
	`#__litdb_LiteratureAudience`,
	`#__litdb_LiteratureContributor`,
	`#__litdb_LiteratureFormat`,
	`#__litdb_LiteratureSubject`,
	`#__litdb_ReportType`,
	`#__litdb_Subject`;